#server:
#  #服务端口
#  port: 8001
#spring:
#  application:
#    #应用名称
#    name: spring-cloud-eureka-server
#eureka:
#  server:
#    #关闭自我保护【用于本地测试时配置-快速剔除失效服务】
#    enable-self-preservation: false
#    #检查失效服务间隔【用于本地测试时配置-快速剔除失效服务】
#    eviction-interval-timer-in-ms: 9000
#  instance:
#    #实例主机名（建议使用IP）
#    hostname: 127.0.0.1
#    #自定义实例ID（默认为 主机名:应用名:端口号）
#    instance-id: ${eureka.instance.hostname}:${server.port}
#  client:
#    #非集群服务配置，不将自己当客户端注册到自己
#    register-with-eureka: false
#    #非集群服务配置，不从服务端拉取服务列表
#    fetch-registry: false
#    #指定eureka集群所有服务地址，逗号分隔
#    #如果当前服务是eureka服务端，当前服务地址也要包含在内，服务地址结构：http://[hostname]:[port]/eureka/
#    #其中hostname建议最好与配置中的eureka.instance.hostname对应，因为服务端会根据hostname从service-url中区分
#    #出本机服务url和集群其它伙伴服务url，如果不对应，会将自身也当成伙伴服务，伙伴服务列表在eureka主页上
#    #DS Replicas部分展示
#    service-url:
#      defaultZone: http://127.0.0.1:8001/eureka/
#management:
#  endpoints:
#    web:
#      exposure:
#        #actuator监控中心，开放所有权限
#        include: '*'

#################################### eureka 集群配置示例 start #################################
#eureka:
#  server:
#    #关闭自我保护【用于本地测试时配置-快速剔除失效服务】
#    enable-self-preservation: false
#    #检查失效服务间隔【用于本地测试时配置-快速剔除失效服务】
#    eviction-interval-timer-in-ms: 1000
#  instance:
#    #实例主机名（建议使用IP）
#    hostname: 127.0.0.1
#    #自定义实例ID
#    instance-id: ${eureka.instance.hostname}:${server.port}
#    #续约更新时间间隔【用于本地测试时配置-快速剔除失效服务】
#    lease-renewal-interval-in-seconds: 3
#    #续约到期时间【用于本地测试时配置-快速剔除失效服务】
#    lease-expiration-duration-in-seconds: 9
#  client:
#    #指定eureka集群所有服务地址，逗号分隔
#    #如果当前服务是eureka服务端，当前服务地址也要包含在内，服务地址结构：http://[hostname]:[port]/eureka/
#    #其中hostname建议最好与配置中的eureka.instance.hostname对应，因为服务端会根据hostname从service-url中区分
#    #出本机服务url和集群其它伙伴服务url，如果不对应，会将自身也当成伙伴服务，伙伴服务列表在eureka主页上
#    #DS Replicas部分展示
#    service-url:
#      defaultZone: http://127.0.0.1:8001/eureka/,http://localhost:8002/eureka/,http://192.168.10.110:8003/eureka/
#################################### eureka 集群配置示例 end #################################
server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
#      单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
