server:
  port: 9527

spring:
  application:
    name: systemcloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:
  #ignored-services: systemcloud-test
  prefix: /ice
  ignored-services: "*"
  routes:
    mytest.serviceId: systemcloud-test
    mytest.path: /mytest/**


info:
  app.name: systemcloud-zuul-gateway
  company.name: www.baidu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}