server: 
  port: 3344 
  
spring:
  application:
    name:  systemcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/a690604371/systemcloud-config.git #GitHub上面的git仓库名字


